### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by lkorth** [Kount/kount-android-sdk#2]
In version 3.1 of the Kount Android SDK there is a race condition that results in data not being collected. If you call `DataCollector#setContext` right before (usually in the same event loop) calling `DataCollector#collectForSession` the failure callback is always called with `DataCollector.Error.CONTEXT_NOT_SET` the first time or whenever the `DataCollector` singleton is not in memory. 

This is a result of the `WebView` being creating inside of a `Handler` on the main thread, `DataCollector#collectForSession` will execute before the `WebView` has been created and the check for the `WebView` will fail and result in the failure callback. Since responses are already communicated back via callbacks it would be nice to wrap the code and check inside of `DataCollector#collectForSession` inside of a `Handler` 

```java
new Handler(Looper.getMainLooper())).post(new Runnable() { 
    public void run() {
        ...
    }
});
```

or similarly alter the check to avoid this race condition.

Thanks!

**Comment by lkorth** [comment]
I've added a [commit](https://github.com/lkorth/kount-android-sdk/commit/029dd235092651fcdce7c43e34ac1907e346b5dc) in a [branch](https://github.com/lkorth/kount-android-sdk/tree/issue-2) in my fork of this repo that simply reproduces this issue.

**Comment by gjd-keynetics** [comment]
The Alternate Implementation described in this workaround seems to workand solves this issue for now.  A more permanent solution is slated for the next release in late Q1/ beginning of Q2.

**Comment by seancc0** [comment]
Fhttp://www.javadoc.io/doc/com.braintreepayments.api/braintreehttp://www.javadoc.io/doc/com.braintreepahttp://www.javadoc.io/doc/com.braintreepayments.api/braintreeyments.api/braintree

**Comment by seancc0** [comment]
Thttp://www.javadoc.io/doc/com.braintreepayments.api/braintree
