### ISSUE TITLE
4.3.0 is broken on jitpack

### ISSUE THREAD

**Issue by Oleksii-Beloborodov** [Kount/kount-android-sdk#25]
Latest Kount version 4.3.0 appear to be broken in jitpack.

Our team tried to update Kount to version 4.3.0, just to find out that it is broken.
Please investigate the issue and prevent it from happening.

Link to correspondent issue reported to jitpack: https://github.com/jitpack/jitpack.io/issues/5580

**Comment by Oleksii-Beloborodov** [comment]
It's now fixed, so I'll close this one, but 4.2.4, 4.2.3 and older remain broken.

**Comment by Oleksii-Beloborodov** [comment]
And now it's broken again. The folder is present, but there is only build.log in it.
https://jitpack.io/com/github/Kount/Kount-android-sdk/v4.3.0/

**Comment by gjd-keynetics** [comment]
You might have a typo (case sensitive) in your URL.  the "K" in the kount-android-sdk should be lower case.  Try this instead:

https://jitpack.io/com/github/Kount/kount-android-sdk/v4.3.0/

**Comment by Oleksii-Beloborodov** [comment]
Hmmm yes, there is a typo indeed.
For some reason though it was working like that for the last 7 month.
Thank you, it fixes my issue. I'll close this and correspondent ticket in jitpack.
