### ISSUE TITLE
Remove "v" from version number.

### ISSUE THREAD

**Issue by Oleksii-Beloborodov** [Kount/kount-android-sdk#27]
In 4.2.3 and 4.2.4a version number looked like this:
`  implementation 'com.github.Kount:Kount-android-sdk:4.2.4a'`

Now in 4.3.0 the leading "v" letter was added that obviously shouldn't be there and affects Android IDE functionality that is monitoring version of libs.

Because now dependency looks like this:
`  implementation 'com.github.Kount:Kount-android-sdk:v4.3.0'`
IDE thinks that this version is older than 4.2.4a.

![02](https://github.com/Kount/kount-android-sdk/assets/58598708/7186005f-c677-44c1-babc-afab406e2584)

It's minor, but still matters.

**Comment by gjd-keynetics** [comment]
Version 4.2.4 is no longer recommended.  Please use 4.3.0 or newer.
