### ISSUE TITLE
Path for gradle dependency is wrong documented

### ISSUE THREAD

**Issue by mlilienberg** [Kount/kount-android-sdk#30]
Following[ this documentation](https://developer.kount.com/hc/en-us/articles/4777351032084) the library jar should be accessible via
`implementation 'com.github.Kount:Kount-android-sdk:v4.3.0'`
instead it published as:
`implementation 'com.github.Kount:kount-android-sdk:4.3.0'`

Not sure if it is a good idea to use upper case in the package name. It is the first time i see this as well as using `v` to prefix the version.

**Comment by gjd-keynetics** [comment]
Thanks for pointing that out.  It was correct on the other pages, but that one had a typo.  It is currently being fixed.

For future reference: We no longer monitor this repository. Please post your question or issue in Kount Community (https://support.kount.com/hc/en-us/community/topics) or email [support@kount.com](mailto:support@kount.com).
